"name": "Dependency review"

"on":
    "pull_request":
        "branches": ["main"]

"permissions": {}

"jobs":
    "dependency-review":
        "permissions":
            "contents": "read"
            "pull-requests": "write"
        "uses": "anolilab/workflows/.github/workflows/dependency-review.yml@9037c2643e28b71d6f625f73686676a9c39761c2" # v23.0.2
